// Build-time generator: downloads Natural Earth 110m country topology and
// emits a simplified, equirectangular-projected SVG path set into
// src/lib/worldGeo.ts. Run with: node scripts/genWorldGeo.mjs
import { writeFileSync } from "node:fs";

const SRC = "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json";
const VIEW_W = 1000;
const VIEW_H = 500;
// Drop rings whose projected bounding box is smaller than this (removes specks).
const MIN_BBOX = 2.2;

function decodeArcs(topology) {
  const { arcs, transform } = topology;
  const [sx, sy] = transform.scale;
  const [tx, ty] = transform.translate;
  return arcs.map((arc) => {
    let x = 0;
    let y = 0;
    return arc.map(([dx, dy]) => {
      x += dx;
      y += dy;
      return [x * sx + tx, y * sy + ty];
    });
  });
}

function arcPoints(absArcs, index) {
  if (index < 0) return absArcs[~index].slice().reverse();
  return absArcs[index];
}

function ringPoints(absArcs, ring) {
  const pts = [];
  ring.forEach((ai, k) => {
    const seg = arcPoints(absArcs, ai);
    (k === 0 ? seg : seg.slice(1)).forEach((p) => pts.push(p));
  });
  return pts;
}

const px = (lng) => ((lng + 180) / 360) * VIEW_W;
const py = (lat) => ((90 - lat) / 180) * VIEW_H;

function ringToPath(points) {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  const proj = points.map(([lng, lat]) => {
    const x = Math.round(px(lng));
    const y = Math.round(py(lat));
    if (x < minX) minX = x;
    if (y < minY) minY = y;
    if (x > maxX) maxX = x;
    if (y > maxY) maxY = y;
    return [x, y];
  });
  if (maxX - minX < MIN_BBOX && maxY - minY < MIN_BBOX) return null;

  // Stroke-only outlines: start a new subpath wherever the polyline jumps the
  // antimeridian (large horizontal delta), so wrapped countries don't streak
  // across the whole map. Rings are already closed (first === last point).
  let d = "";
  let prev = null;
  proj.forEach((p) => {
    if (prev && p[0] === prev[0] && p[1] === prev[1]) return; // dedupe
    const jump = prev && Math.abs(p[0] - prev[0]) > 500;
    d += !prev || jump ? `M${p[0]} ${p[1]}` : `L${p[0]} ${p[1]}`;
    prev = p;
  });
  return d || null;
}

function geometryToPath(absArcs, geom) {
  const polygons =
    geom.type === "Polygon" ? [geom.arcs] : geom.type === "MultiPolygon" ? geom.arcs : [];
  let d = "";
  for (const poly of polygons) {
    for (const ring of poly) {
      const rp = ringToPath(ringPoints(absArcs, ring));
      if (rp) d += rp;
    }
  }
  return d;
}

const res = await fetch(SRC);
if (!res.ok) throw new Error(`Fetch failed: ${res.status}`);
const topology = await res.json();
const absArcs = decodeArcs(topology);
const collection = topology.objects.countries;

const SKIP = new Set([10]); // Antarctica

const countries = [];
for (const geom of collection.geometries) {
  const id = Number(geom.id) || 0;
  if (SKIP.has(id)) continue;
  const d = geometryToPath(absArcs, geom);
  if (!d) continue;
  countries.push({ id, d });
}

const file = `// AUTO-GENERATED by scripts/genWorldGeo.mjs — do not edit by hand.
// Simplified Natural Earth 110m countries, equirectangular projection.
export const WORLD_VIEWBOX = "0 0 ${VIEW_W} ${VIEW_H}";
export const WORLD_W = ${VIEW_W};
export const WORLD_H = ${VIEW_H};

/** Equirectangular projection into the map viewBox. */
export function projectLngLat(lng: number, lat: number): { x: number; y: number } {
  return { x: ((lng + 180) / 360) * ${VIEW_W}, y: ((90 - lat) / 180) * ${VIEW_H} };
}

export interface CountryPath {
  /** Numeric ISO 3166-1 code. */
  id: number;
  /** SVG path data in the map viewBox. */
  d: string;
}

export const worldCountries: CountryPath[] = ${JSON.stringify(countries)};
`;

writeFileSync(new URL("../src/lib/worldGeo.ts", import.meta.url), file, "utf8");
console.log(
  `Wrote ${countries.length} countries, ${(file.length / 1024).toFixed(1)} KB`,
);
